-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgqroYFhjIiMyBGov3
F2wtpgahR9oPueiWJHhQx/KdYNegCgYIKoZIzj0DAQehRANCAARHBzHXqZZ5/8xw
E4Wu+QYhX6Ug4rJdcSCkyUzo/0sFjVWezgFjHaxkSDFKFWA2xrr2UphfFey/8tfE
AEkBTuWy
-----END PRIVATE KEY-----